spring:
  application:
    name: microservice-service-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/3babydaddy/spring-cloud-config.git
          search-paths: respo
          username: 3babydaddy
          password: P@ssw0rdxl

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/